language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
    - sourceline: 'deb http://download.telldus.com/debian/ stable main'
    - key_url: 'http://download.telldus.se/debian/telldus-public.key'
    packages:
    - gcc-4.8
    - g++-4.8
    - libtelldus-core-dev
    - telldus-core
